import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

pw.Widget buildPdfFooter({
  required pw.Context ctx,
  required PdfColor borderColor,
  required PdfColor subtleColor,
  pw.MemoryImage? nexusIcon,
}) {
  return pw.Container(
    padding: const pw.EdgeInsets.symmetric(horizontal: 40, vertical: 12),
    child: pw.Column(
      mainAxisSize: pw.MainAxisSize.min,
      children: [
        pw.Container(height: 1, color: borderColor),
        pw.SizedBox(height: 12),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Row(
              children: [
                pw.Text(
                  'Generated by N.O.D.E. Wholesale Platform',
                  style: pw.TextStyle(fontSize: 8, color: subtleColor),
                ),
                pw.SizedBox(width: 8),
                pw.Container(width: 1, height: 8, color: borderColor),
                pw.SizedBox(width: 8),
                pw.Text(
                  'in association with NEXUS',
                  style: pw.TextStyle(fontSize: 8, color: subtleColor, fontWeight: pw.FontWeight.bold),
                ),
                if (nexusIcon != null) ...[
                  pw.SizedBox(width: 8),
                  pw.Container(
                    width: 12,
                    height: 12,
                    child: pw.Image(nexusIcon),
                  ),
                ],
              ],
            ),
            pw.Text(
              'Page ${ctx.pageNumber}${ctx.pagesCount != null ? ' of ${ctx.pagesCount}' : ''}',
              style: pw.TextStyle(fontSize: 8, color: subtleColor),
            ),
          ],
        ),
      ],
    ),
  );
}
